model:
  # Name / revision to save model as
  base: "CityAesthetics-Anime"
  rev:  "v1.8"
  # Model architecture. 'score' or 'class'
  arch: score
  # CLIP for openai/clip-vit-large-patch14
  # META for metaclip_fullcc|ViT-H-14-quickgelu
  clip: CLIP

train:
  lr:    7e-6     # init. learning rate
  steps: 100000   # no. of training steps
  batch: 1        # training batch size
  cosine: True    # Use cosine scheduler
